name         'rfletcher-chromedriver'
version      '0.0.1'
license      'MIT License'
summary      'A Puppet module for Chrome Driver'
description  'Install or remove Chrome Driver'
project_page 'https://github.com/rfletcher/puppet-chromedriver'
dependency   'camptocamp/archive', '>= 0.1.0'
dependency   'example42/zip'
